---
title: 'SC processing'
author: "FHIL\nDerrikGratz"
date: '`r Sys.Date()`'
output: html_document
---

```{r, include=FALSE}
knitr::opts_chunk$set(echo = FALSE,
                      fig.width = 8, fig.height = 6,
                      cache=FALSE, cache.lazy = FALSE) 

library(tidyverse)  ## General R logic
library(here)       ## Easier specification of file locations
library(yaml)       ## parses config yaml
library(Seurat)
library(reshape2)   ## DF manipulation
# library(clustree)   ## Resolution selection for clustering
# library(ggraph)     ## To render clustree
library(SingleR)
library(SingleCellExperiment)
rbindlist <- data.table::rbindlist
set.seed(33)
```

# Load data

```{r}
objs <- readRDS(here('rds/02-filtered_objs.rds'))
metadata <- read.csv(here('config/metadata.csv'))
figures <- list()
```

# Data normalization and processing

```{r}
objs <- lapply(objs, NormalizeData)
objs <- lapply(objs, FindVariableFeatures)
objs <- lapply(objs, ScaleData)
objs <- lapply(objs, RunPCA)
```

```{r}
#Check if 30 dims is appropriate
lapply(objs, ElbowPlot, ndim=30)
```

```{r}
objs <- lapply(objs, FindNeighbors, dims=1:20, graph.name=c('RNA_NN', 'RNA_SNN'))
objs <- lapply(objs, RunUMAP, dims=1:20)
```

# Reference annotation

```{r run_SingleR}
runSingleR <- function(obj.seurat,
                       ref,
                       labels,
                       de.method = "classic",
                       meta.prefix = 'singleR',
                       num.threads = BiocParallel::bpnworkers(BiocParallel::MulticoreParam()),
                       ...) {
  singleR.out <- obj.seurat %>%
    Seurat::as.SingleCellExperiment(assay = "RNA") %>%
    scuttle::logNormCounts() %>%
    SummarizedExperiment::assays() # %>%
    # .$logcounts %>%
  singleR.out <- SingleR::SingleR(test = singleR.out$logcounts,
                     ref = ref,
                     labels = labels,
                     de.method = de.method,
                     num.threads = num.threads,
                     ...)

  obj.seurat@meta.data[[paste0(meta.prefix,".labels")]] <- singleR.out$labels
  obj.seurat@meta.data[[paste0(meta.prefix,".pruned.labels")]] <- singleR.out$pruned.labels
  obj.seurat@meta.data[[paste0(meta.prefix,".delta.next")]] <- singleR.out$delta.next

  return(obj.seurat)
}
```

## Novershtern

```{r}
ref <- readRDS('/fh/fast/_IRC/FHIL/pub/ref/single_cell_references/Novershtern_celldex.rds')
objs <- lapply(objs, function(x) {
  runSingleR(x, 
             ref = assays(ref)$logcounts,
             labels = ref$label.main,
             meta.prefix = 'Novershtern.main',
             de.method = 'wilcox')
  })
```

## HPCA

```{r}
ref <- readRDS('/fh/fast/_IRC/FHIL/pub/ref/single_cell_references/HPCA_celldex.rds')
objs <- lapply(objs, function(x) {
  runSingleR(x, 
             ref = assays(ref)$logcounts,
             labels = ref$label.main,
             meta.prefix = 'HPCA.main',
             de.method = 'wilcox')
  })
```

# Fixed resolution

```{r}
objs <- lapply(objs, FindClusters, resolution=1.0, graph.name='RNA_NN', algorithm=4, cluster.name='res_1.0_clusters')
```

## Silhouette

```{r}
library(bluster)
tmp <- bluster::approxSilhouette(objs$Flex_F1A@reductions$PCA, objs$Flex_F1A$res_1.0_clusters)
```



# SC3 resolution selection

```{r}
objs_SCE <- lapply(objs, function(x) {
  x <- Seurat::as.SingleCellExperiment(x)
  rowData(x)$feature_symbol <- rownames(x)
  x <- x[!duplicated(rowData(x)$feature_symbol), ]
  x
})
```

```{r}
calculate_distance <- function(data, method) {
    return(if (method == "spearman") {
        as.matrix(1 - cor(data, method = "spearman"))
    } else if (method == "pearson") {
        as.matrix(1 - cor(data, method = "pearson"))
    } else {
        ED2(data)
    })
}
```

```{r}
tmp <- SC3::sc3_prepare(objs_SCE$Flex_F1A, gene_filter=FALSE)
tmp <- SC3::sc3_estimate_k(tmp)
tmp <- sc3_calc_dists(tmp)
tmp <- sc3_calc_transfs(tmp)
str(metadata(tmp)$sc3)
```

# Render report

```{r, eval=TRUE}
## This only works if all the variables called in the format file 
## are in the current environment. Check the format file to tweak
## aesthetics 
rmarkdown::render(here('scripts/03-clustering.format.Rmd'),
                  output_file = '10x_3p+felx_QC_figs.html',
                  output_dir = here('reports'))
```
