---
title: 'SC processing'
author: "FHIL\nDerrikGratz"
date: '`r Sys.Date()`'
output: html_document
---

```{r, include=FALSE}
knitr::opts_chunk$set(echo = FALSE,
                      fig.width = 8, fig.height = 6,
                      cache=FALSE, cache.lazy = FALSE) 

library(tidyverse)  ## General R logic
library(here)       ## Easier specification of file locations
library(yaml)       ## parses config yaml
library(Seurat)
# library(reshape2)   ## DF manipulation
library(clustree)   ## Resolution selection for clustering
library(ggraph)     ## To render clustree
rbindlist <- data.table::rbindlist
set.seed(33)
```

```{r}
figures <- list()
```

# Load data

```{r}
objs <- readRDS(here('rds/03-filtered_objs.rds'))
```

# Reprocessing

```{r}
objs <- lapply(objs, NormalizeData)
objs <- lapply(objs, FindVariableFeatures)
objs <- lapply(objs, ScaleData)
objs <- lapply(objs, RunPCA)
```

```{r}
lapply(objs, ElbowPlot)
```

```{r}
objs <- lapply(objs, FindNeighbors, dims=1:15)
objs <- lapply(objs, RunUMAP, dims=1:15)
```

# Clustering

```{r}
objs <- lapply(objs, RunPCA)
objs <- lapply(objs, FindNeighbors, dims=1:30)
objs <- lapply(objs, RunUMAP, dims=1:30)
```

## Resolution selection

```{r}
createClustree <- function(obj,
                           res = c(seq(0.1,1.5, .1), 2, 3, 5), ...) {
  for (i in res) {
    obj <- Seurat::FindClusters(obj, res=i)
  }
  clustree::clustree(obj, ...)
}

clustrees <- lapply(objs, createClustree)

for ( i in names(clustrees)){
  clustrees[[i]] <- clustrees[[i]] + ggtitle(i)
}
```

```{r, fig.height=12}
clustrees
```

```{r}
resolutions <- list(
 "GEMX5P_F1" = 1.1,
 "GEMX5P_F2" = 1.0,
 "GEMX5P_F4" = 0.8,
 "GEMX5P_F5" = 0.8,
 "NextGEM_F1" = 0.9,
 "NextGEM_F2" = 1.0,
 "NextGEM_F4" = 1.0,
 "NextGEM_F5" = 1.3,
 "PA_1_F1" = 1.1,
 "PA_1_F2" = 1.1,
 "PA_1_F4" = 1.1,
 "PA_1_F5" = 1.2,  
 "FB_2_F1A" = 1.3,
 "FB_2_F1B" = 1.3,
 "FB_2_F5A" = 1.2,
 "FB_2_F5B" = 1.0,
 "GEMX3P_F1A" = 1.2,
 "GEMX3P_F1B"= 1.0,
 "GEMX3P_F5A" = 1.0,
 "GEMX3P_F5B" = 1.0,
 "PA_2_F1A" = 1.2,
 "PA_2_F1B" = 1.5,
 "PA_2_F5A" = 1.1,
 "PA_2_F5B" = 1.5
)
```

## Run findclusters

```{r}
for (sample in names(objs)){
  objs[[sample]] <- Seurat::FindClusters(objs[[sample]], resolution = resolutions[[sample]])
}
```


# Resolution selection

```{r}
createClustree <- function(obj,
                           res = c(seq(0.1,1.5, .1), 2, 3, 5), ...) {
  for (i in res) {
    obj <- Seurat::FindClusters(obj, res=i)
  }
  clustree::clustree(obj, ...)
}

clustrees <- lapply(objs, createClustree)
labels <- names(clustrees)
for (i in labels) {
  clustrees[[i]] <- clustrees[[i]] + ggtitle(i)
}
```

```{r, fig.height=12}
clustrees
```

```{r}
resolutions <- list(
  GEMX_F1 = 1.0,
  GEMX_F2 = 0.9,
  GEMX_F4 = 1.1,
  GEMX_F5 = 1.0,
  NextGEM_F1 = 1.2,
  NextGEM_F2 = 0.9,
  NextGEM_F4 = 1.5,
  NextGEM_F5 = 1.4,
  PA_1_F1 = 1.2,
  PA_1_F2 = 1.2,
  PA_1_F4 = 0.9,
  PA_1_F5 = 0.9,
  FB_2_F1A = 1.5,
  FB_2_F1B = 1.5,
  FB_2_F5A = 1.3,
  FB_2_F5B = 1.4,
  GEMX_F1A = 1.1,
  GEMX_F1B = 1.0,
  GEMX_F5A = 0.7,
  GEMX_F5B = 0.8,
  PA_2_F1A = 1.0,
  PA_2_F1B = 1.2,
  PA_2_F5A = 0.7,
  PA_2_F5B = 1.0
)
```

## Run findclusters

```{r}
for (sample in names(objs)){
  objs[[sample]] <- Seurat::FindClusters(objs[[sample]], resolution = resolutions[[sample]])
}
```

## Dimplots

```{r}
lapply(names(objs), function(x){
  DimPlot(objs[[x]]) + ggtitle(x)
})
```

# Celltype annotations

```{r run_SingleR}
runSingleR <- function(obj.seurat,
                       ref,
                       labels,
                       de.method = "classic",
                       meta.prefix = 'singleR',
                       num.threads = BiocParallel::bpnworkers(BiocParallel::MulticoreParam()),
                       ...) {
  singleR.out <- obj.seurat %>%
    Seurat::as.SingleCellExperiment(assay = "RNA") %>%
    scuttle::logNormCounts() %>%
    SummarizedExperiment::assays() # %>%
    # .$logcounts %>%
  singleR.out <- SingleR::SingleR(test = singleR.out$logcounts,
                     ref = ref,
                     labels = labels,
                     de.method = de.method,
                     num.threads = num.threads,
                     ...)

  obj.seurat@meta.data[[paste0(meta.prefix,".labels")]] <- singleR.out$labels
  obj.seurat@meta.data[[paste0(meta.prefix,".pruned.labels")]] <- singleR.out$pruned.labels
  obj.seurat@meta.data[[paste0(meta.prefix,".delta.next")]] <- singleR.out$delta.next

  return(obj.seurat)
}
```

```{r}
ref <- readRDS('/fh/fast/_IRC/FHIL/pub/ref/single_cell_references/Novershtern_celldex.rds')
objs <- lapply(objs, function(x) {
  runSingleR(x, 
             ref = assays(ref)$logcounts,
             labels = ref$label.main,
             meta.prefix = 'Novershtern.main',
             de.method = 'wilcox')
  })
```

```{r}
ref <- readRDS('/fh/fast/_IRC/FHIL/pub/ref/single_cell_references/HPCA_celldex.rds')
objs <- lapply(objs, function(x) {
  runSingleR(x, 
             ref = assays(ref)$logcounts,
             labels = ref$label.main,
             meta.prefix = 'HPCA.main',
             de.method = 'wilcox')
  })
```

```{r}
lapply(objs, function(x) {
  DimPlot(x, group.by = 'Novershtern.main.pruned.labels')
})

```

# Celltype predictions

## Novershtern

```{r}
lapply(names(objs), function(x){
  DimPlot(objs[[x]], group.by = 'Novershtern.main.pruned.labels', label = TRUE) + ggtitle(x)
})
```

## HPCA

```{r}
lapply(names(objs), function(x){
  DimPlot(objs[[x]], group.by = 'HPCA.main.pruned.labels', label = TRUE) + ggtitle(x)
})
```

## Top cluster annotations

```{r}
extract_cluster_annotations <- function(data, singleR_data_prefixes) {
  results <- list()
  for (dataset in singleR_data_prefixes) {
    labels <- paste0(dataset, '.pruned.labels')
    delta_next <- paste0(dataset, '.delta.next')
    results[[dataset]] <- data@meta.data %>%
      select(seurat_clusters, .data[[labels]], .data[[delta_next]]) %>%
      group_by(seurat_clusters, .data[[labels]]) %>%
      summarise(n = n(),
                med.delta.next = round(median(.data[[delta_next]]),2), .groups = 'drop_last') %>%
      mutate(total_cells = sum(n),
             percent = round(n / total_cells * 100, 2)) %>%
      slice_max(n, with_ties = FALSE) %>%
      select(-n) %>%
    rename_with(~ paste0(dataset, '.', .x), .cols = c('percent', 'med.delta.next'))
  }
  if (length(singleR_data_prefixes) > 1) {
    results <- Reduce(function(x,y) merge(results[[x]],results[[y]], by=c('seurat_clusters', 'total_cells')), 1:length(results))
  } else {
    results <- results[[1]]
  }
  results <- results %>% arrange(seurat_clusters)
}
```

```{r}
cluster_annotations <- lapply(objs, extract_cluster_annotations, c('HPCA.main', 'Novershtern.main'))
```


```{r}
cluster_annotations$GEMX_F1 %>%
  datatable(rownames = FALSE,
    options = list(pageLength = 22,
                   searching=FALSE,
                   ordering=FALSE,
                   lengthChange = FALSE)) %>%
  formatStyle(c('Novershtern.main.percent', 'HPCA.main.percent'),
              background = styleColorBar(range(c(0,100)), 'lightblue'))  %>%
  formatStyle(c('HPCA.main.med.delta.next', 'Novershtern.main.med.delta.next'),
              background = styleInterval(seq(0,0.9,.1), rgb(0,1,0,brks))) %>%
  formatStyle(
    c('Novershtern.main.pruned.labels', 'HPCA.main.pruned.labels'),
    `border-right` = styleEqual(1, 'solid 3px')
  )
```

