---
title: 'SC processing'
author: "FHIL\nDerrikGratz"
date: '`r Sys.Date()`'
output: html_document
---

```{r, include=FALSE}
knitr::opts_chunk$set(echo = FALSE,
                      fig.width = 8, fig.height = 6,
                      cache=FALSE, cache.lazy = FALSE) 

library(tidyverse)  ## General R logic
library(here)       ## Easier specification of file locations
library(yaml)       ## parses config yaml
library(Seurat)
library(reshape2)   ## DF manipulation
# library(clustree)   ## Resolution selection for clustering
# library(ggraph)     ## To render clustree
# library(ggforestplot) ## Striped lines for dotplots
# library(SingleCellExperiment)
library(gridExtra)  ## arrange plots
# library(janitor) ## Tabyl, adorn_rounding
# library(ggrastr) ## Rasterize images for smaller size
library(DT)     ## Datatables
rbindlist <- data.table::rbindlist
set.seed(33)
```

# Functions

# Load data

```{r}
objs <- readRDS(here('rds/05_objs_post_clustering.rds'))
metadata <- read.csv(here('config/metadata.csv'))
figures <- list()
```

# Generate scCoda data

```{r, eval = TRUE}
comp_table <-  lapply(objs, function(x) {
  tabyl(x$cell_labels.coarse)
  }) |> rbindlist(idcol = 'Sample') 
comp_table <- dcast.data.table(comp_table, Sample ~ `x$cell_labels.coarse`, value.var = 'n') %>%
  mutate_all(~replace(., is.na(.), 0)) 
comp_table <- merge(comp_table, metadata, by='Sample')

write.table(x = comp_table, file = here('rds/composition_table_coarse.txt'),
            quote = FALSE, row.names = FALSE, col.names = TRUE, sep = '\t')
```

# Plot

```{r, fig.height=4, warning=FALSE, fig.width=15}
comp_table <-  lapply(objs, function(x) {
  y <- tabyl(x$cell_labels.coarse)
  colnames(y) <- c('Celltype', 'n', 'percent')
  y
  }) |> rbindlist(idcol = 'Sample') |>
  mutate_all(~replace(., is.na(.), 0)) 

## Adding missing counts
if (FALSE){
  all_combinations <- expand.grid(Sample = unique(comp_table$Sample),
                                  Celltype = unique(comp_table$Celltype))
  
  comp_table <- merge(all_combinations, comp_table,
                      by = c("Sample", "Celltype"), all.x = TRUE)
  comp_table$percent[is.na(comp_table$percent)] <- 0
}

comp_table <- merge(comp_table, metadata, by='Sample')
comp_table %>%
  ggplot(aes(x = Kit, y = percent,
             group = Kit, color = Kit, shape = paste0(Individual, Replicate))) + 
  geom_point() +
  labs(x = element_blank(), y = 'Proportion of sample',
       color = 'Kit', shape='Sample',
       caption = paste(
         'Portions are of the total capture for a sample.',
         # '* = significant below 0.05 FDR',
         sep='\n')) +
  theme_bw() +
  scale_shape_manual(values = c(1:5))+ 
  theme(axis.text.x = element_blank(), axis.ticks.x = element_blank()) +
  facet_grid(~ factor(Celltype), scales='free_y')
  ## This is known to be significant from the scCODA results
  # geom_signif(data = data.frame(full_labels = 'pDC',
  #                               label = '*',
  #                               y = .035,
  #                               start = 1.5, end = 3.5,
  #                               outlier = NA),
  #             aes(annotations = label, y_position = y,
  #                 xmin = start, xmax = end),
  #             inherit.aes = FALSE,
  #             tip_length = -0.03,
  #             margin_top = -0.02,
  #             vjust = 2.5,
  #             manual = TRUE, map_signif_level = TRUE)
# pre_vs_post_coarse_comp_boxplot
# ggsave(here('outputs/innate/DC+monocyte/composition_boxplot.png'), height = 4, width = 15)
```

# Save objs

```{r, eval=TRUE}
# saveRDS(objs, here('rds/06_''), compress=FALSE)
```

# Render report

```{r, eval=FALSE}
## This only works if all the variables called in the format file 
## are in the current environment. Check the format file to tweak
## aesthetics 
rmarkdown::render(here('processing_scripts/06-composition.format.Rmd'),
                  output_file = '06-composition.html',
                  output_dir = here('reports'))
```
