---
title: 'scRNA QC'
author: "FHIL\nDerrikGratz"
date: '`r Sys.Date()`'
output: html_document
---

```{r, include=FALSE}
knitr::opts_chunk$set(echo = FALSE,
                      fig.width = 8, fig.height = 6,
                      cache=FALSE, cache.lazy = FALSE) 

library(tidyverse)  ## General R logic
library(here)       ## Easier specification of file locations
library(yaml)       ## parses config yaml
library(Seurat)
library(reshape2)   ## DF manipulation
# library(celldex)    ## Reference datasets for celltype annotation
library(SingleCellExperiment) ## Doublet detection dependency
library(scDblFinder) ## Doublet detection
library(clustree)   ## Resolution selection for clustering
library(ggraph)     ## To render clustree
library(scuttle)    ## various SC utilities
set.seed(33)
```

# Functions

```{r}
addQCMetrics <- function(obj, mt_pattern = '^MT', rb_pattern = '^RP[SL]') {
    obj$log10GenesPerUMI <- log10(obj$nFeature_RNA)/log10(obj$nCount_RNA)
    obj$mtRatio <- PercentageFeatureSet(obj, pattern=mt_pattern) / 100
    obj$rbRatio <- PercentageFeatureSet(obj, pattern=rb_pattern) / 100
    obj
}
```

# Load data

```{r}
objs <- readRDS(here('rds/01_raw_objs.rds'))
```

# Processing

## Rename cells

```{r}
## Renaming cells with the sample name to avoid conflicts with references, merging etc.
objs <- lapply(objs, function(sample){
  RenameCells(sample, add.cell.id = unique(sample$orig.ident))
})
```

```{r}
objs <- lapply(objs, addQCMetrics)
```

## Normalize

```{r}
objs <- lapply(objs, NormalizeData)
objs <- lapply(objs, FindVariableFeatures)
objs <- lapply(objs, ScaleData)
```


## Doublets

```{r}
run_scDblFinder <- function(obj,
                            knownDoublets=NULL,
                            knownUse=NULL,
                            nfeatures = 2000,
                            ...){
  if (!is.null(knownDoublets)) {
    if (is.null(knownUse)) {
      errorCondition('Specify how you want known doublets to be used with "knownUse"')
    }
  }
  obj.sce <- Seurat::as.SingleCellExperiment(obj)
  obj.sce <- scDblFinder::scDblFinder(obj.sce,
                                      knownDoublets = knownDoublets,
                                      knownUse = knownUse,
                                      nfeatures = nfeatures,
                                      ...)
  obj$scDblFinder.score <- obj.sce$scDblFinder.score
  obj$scDblFinder.class <- obj.sce$scDblFinder.class
  obj
}
```

```{r}
objs <- lapply(objs,
               run_scDblFinder,
               dbr.sd=1 ## per github, if unsure about doublet rate
)
```

## Clustering

```{r}
objs <- lapply(objs, RunPCA)
objs <- lapply(objs, FindNeighbors, dims=1:30)
objs <- lapply(objs, RunUMAP, dims=1:30)
```

### Resolution selection

```{r}
createClustree <- function(obj,
                           res = c(seq(0.1,1.5, .1), 2, 3, 5), ...) {
  for (i in res) {
    obj <- Seurat::FindClusters(obj, res=i)
  }
  clustree::clustree(obj, ...)
}

clustrees <- lapply(objs, createClustree)
```

```{r, fig.height=12}
clustrees$GEMX_F5B
```

```{r}
resolutions <- list(
  GEMX_F1 = 1.0,
  GEMX_F2 = 1.1,
  GEMX_F4 = 1.2,
  GEMX_F5 = 1.4,
  NextGEM_F1 = 2,
  NextGEM_F2 = 1.4,
  NextGEM_F4 = 1.5,
  NextGEM_F5 = 1.4,
  PA_1_F1 = 1.5,
  PA_1_F2 = 1.4,
  PA_1_F4 = 0.7,
  PA_1_F5 = 0.8,
  FB_2_F1A = 0.9,
  FB_2_F1B = 1.0,
  FB_2_F5A = 1.4,
  FB_2_F5B = 3,
  GEMX_F1A = 0.7,
  GEMX_F1B = 1.0,
  GEMX_F5A = 0.9,
  GEMX_F5B = 1.2
)
```

### Run findclusters

```{r}
for (sample in names(objs)){
  objs[[sample]] <- Seurat::FindClusters(objs[[sample]], resolution = resolutions[[sample]])
}
```

# Celltype annotations

```{r run_SingleR}
runSingleR <- function(obj.seurat,
                       ref,
                       labels,
                       de.method = "classic",
                       meta.prefix = 'singleR',
                       num.threads = BiocParallel::bpnworkers(BiocParallel::MulticoreParam()),
                       ...) {
  singleR.out <- obj.seurat %>%
    Seurat::as.SingleCellExperiment(assay = "RNA") %>%
    scuttle::logNormCounts() %>%
    SummarizedExperiment::assays() # %>%
    # .$logcounts %>%
  singleR.out <- SingleR::SingleR(test = singleR.out$logcounts,
                     ref = ref,
                     labels = labels,
                     de.method = de.method,
                     num.threads = num.threads,
                     ...)

  obj.seurat@meta.data[[paste0(meta.prefix,".labels")]] <- singleR.out$labels
  obj.seurat@meta.data[[paste0(meta.prefix,".pruned.labels")]] <- singleR.out$pruned.labels
  obj.seurat@meta.data[[paste0(meta.prefix,".delta.next")]] <- singleR.out$delta.next

  return(obj.seurat)
}
```

```{r}
ref <- readRDS('/fh/fast/_IRC/FHIL/pub/ref/single_cell_references/Novershtern_celldex.rds')
objs <- lapply(objs, function(x) {
  runSingleR(x, 
             ref = assays(ref)$logcounts,
             labels = ref$label.main,
             meta.prefix = 'Novershtern.main',
             de.method = 'wilcox')
  })
```

```{r}
ref <- readRDS('/fh/fast/_IRC/FHIL/pub/ref/single_cell_references/HPCA_celldex.rds')
objs <- lapply(objs, function(x) {
  runSingleR(x, 
             ref = assays(ref)$logcounts,
             labels = ref$label.main,
             meta.prefix = 'HPCA.main',
             de.method = 'wilcox')
  })
```

```{r}
lapply(objs, function(x) {
  DimPlot(x, group.by = 'Novershtern.main.pruned.labels')
})

```

# Save objs

```{r}
saveRDS(objs, here('rds/01_annotated_objs.rds'))
```

