---
title: 'SC processing'
author: "FHIL\nDerrikGratz"
date: '`r Sys.Date()`'
output: html_document
---

```{r, include=FALSE}
knitr::opts_chunk$set(echo = FALSE,
                      fig.width = 8, fig.height = 6,
                      cache=FALSE, cache.lazy = FALSE) 
library(biomaRt)
library(tidyverse)  ## General R logic
library(here)       ## Easier specification of file locations
library(yaml)       ## parses config yaml
library(Seurat)
library(reshape2)   ## DF manipulation
library(DT)     ## Datatables
rbindlist <- data.table::rbindlist
library(patchwork)
set.seed(33)
```

```{r}
human = useMart(biomart="ensembl", dataset = "hsapiens_gene_ensembl", verbose = TRUE)
INFO <- getBM(attributes = c("ensembl_gene_id",
                             "external_gene_name",
                             "gene_biotype",
                             "transcript_length",
                             "percentage_gene_gc_content",
                             "chromosome_name"),
              mart = human)
info <- INFO |>
  group_by(ensembl_gene_id, gene_biotype, external_gene_name) |>
  summarize(med_transcript_length = median(transcript_length),
            mean_transcript_length = mean(transcript_length))
```

```{r}
objs <- readRDS(here('rds/3p/05_merged_objs_post_clustering.rds'))
```

```{r}
 q <- quantile(x1$med_transcript_length,probs=seq(0.2,1,0.2))
  gene.grp <- cut(sqrt(length), breaks=c(0,q),ordered_result = TRUE)
  
  q2 <- c(0,q^2)
  labels <- rep(NA,5)
  for(i in 1:5) labels[i] <-paste(round(q2[i]),"-",round(q2[i+1]),sep="")
  levels(gene.grp) <- labels
  return(gene.grp)
```


```{r}
check <- function(obj){
  x <- rowSums(GetAssayData(obj, assay='RNA', layer='data')) |>
  as.data.frame() |>
  rownames_to_column('gene') 
colnames(x) <- c('gene', 'expression')
  x1 <- merge(x, info, by.x='gene', by.y='external_gene_name', all.x=TRUE) |>
    filter(!is.na(mean_transcript_length ))
  fit <- lm(expression ~ mean_transcript_length, data = x1) 
  fit |> summary()
}

fit_res <- lapply(objs, check)
```

```{r}
myplot <- function(obj) {
x <- rowSums(GetAssayData(obj, assay='RNA', layer='data')) |>
  as.data.frame() |>
  rownames_to_column('gene') 
colnames(x) <- c('gene', 'expression')
x1 <- merge(x, info, by.x='gene', by.y='external_gene_name', all.x=TRUE) |>
  filter(!is.na(mean_transcript_length ))
ggplot(x1, aes(x=med_transcript_length, y=expression)) +
  geom_point() +
  scale_x_log10() +
  scale_y_log10() + 
  # geom_abline() +
  geom_hline(yintercept = mean(x$expression)) +
  geom_smooth()
}
plots <- lapply(objs, myplot)
```

```{r}
fit_res
```


```{r}
for (x in names(plots)) {
  print(plots[[x]] + ggtitle(x))
}
```

```{r}
tmpfunc <- function(obj){
  x <- rowSums(GetAssayData(obj, assay='RNA', layer='data')) |>
    as.data.frame() |>
    rownames_to_column('gene') 
  colnames(x) <- c('gene', 'expression')
  x1 <- merge(x, info, by.x='gene', by.y='external_gene_name', all.x=TRUE) |>
    filter(!is.na(mean_transcript_length )) |> 
    mutate(length_bin = ntile(mean_transcript_length, 5),
           expression_bin = ntile(expression, 5)) 
  x1 |>
    group_by(length_bin) |>
    summarize(y = sum(expression))
}
plotdata <- rbindlist(lapply(objs, tmpfunc), idcol='kit')
ggplot(plotdata, aes(x=length_bin, y=y)) +
  geom_col() +
  labs(x='Length quantile bin', y = 'Total expression') +
  facet_wrap(~ kit, nrow=2)
```

```{r, fig.height=4, fig.width=12}
plots2 <- list()
for (kit in c('Flex', 'NextGEM3P', 'GEMX3P', 'Scale')) {
  plots2[[kit]] <- 
  ggplot(tmpfunc(objs[[kit]]), aes(x=length_bin, y=y)) +
  geom_col() +
  labs(x='Length quantile bin', y = 'Total expression', 
       caption = paste0('coef = ', round(fit_res[[kit]]$coefficients[2,1], 2),
                        '\nPr(>|t|) = ', signif(fit_res[[kit]]$coefficients[2,4], 2)),
       title = kit) 
}
ggpubr::ggarrange(plotlist =  plots2, nrow=1)
```


