---
title: 'scRNA QC'
author: "FHIL\nDerrikGratz"
date: '`r Sys.Date()`'
output: html_document
---

```{r, include=FALSE}
knitr::opts_chunk$set(echo = FALSE,
                      fig.width = 8, fig.height = 6,
                      cache=FALSE, cache.lazy = FALSE) 

library(tidyverse)  ## General R logic
library(here)       ## Easier specification of file locations
library(yaml)       ## parses config yaml
library(reshape2)   ## DF manipulation
library(immunarch)  ## repertoire analyses
library(ggbeeswarm) ## swarm plots
# library(scuttle)    ## various SC utilities
# library(ggrastr)    ## rasterized point layers for reduced image size
set.seed(33)
```

# Read TCR

```{r}
source(here('config/5p/generate_metadata.R'))
metadata <- read.csv(here('config/5p/metadata.csv'))
```

```{r}
objs <- list()
figures <- list()
```

## gemx_5p

```{r}
kit <- 'gemx_5p'
for (i in 1:nrow(samplesheets[[kit]])){
  sample <- samplesheets[[kit]][i,'Sample']
  file <- samplesheets[[kit]][i,'File']
  
  vdj_data <- file.path(config$base_dir, config$data_dir, data_dirs[[kit]], file,
                               'outs', 'per_sample_outs', file, 'vdj_t', 'filtered_contig_annotations.csv')
  vdj_data <- repLoad(vdj_data)
  vdj_data$data <- vdj_data$data$filtered_contig_annotations
  objs[[sample]] <- vdj_data
}
```

## nextgem_5p

```{r}
kit <- 'nextgem_5p'
for (i in 1:nrow(samplesheets[[kit]])){
  sample <- samplesheets[[kit]][i,'Sample']
  file <- samplesheets[[kit]][i,'File']
  vdj_data <- file.path(config$base_dir, config$data_dir, data_dirs[[kit]], file,
                               'outs', 'per_sample_outs', file, 'vdj_t', 'filtered_contig_annotations.csv')
  vdj_data <- repLoad(vdj_data)
  vdj_data$data <- vdj_data$data$filtered_contig_annotations
  objs[[sample]] <- vdj_data
}
```

## parse_v2

```{r}
repload_parse <- function(file){
    
  # Each non-multiplet cell is present only once, but may not have both chains. 
  # Multiplets are included in base file
  # The clonotype_frequency file groups clonotypes by TRA TRB AA sequence. 
  # It does not include/consider C genes
  barcode_report <- read.table(file, sep='\t', header=TRUE) 
  
  barcode_report <- barcode_report |>
    group_by(TRB_cdr3_aa, TRA_cdr3_aa, secondary_TRB_cdr3_aa, secondary_TRA_cdr3_aa) |>
    summarise(clonotype_count = n(), .groups = "drop") |>
    arrange(desc(clonotype_count)) |>
    mutate(clonotype_id = paste0('clonotype_', row_number())) |>
    right_join(barcode_report, by = c("TRB_cdr3_aa", "TRA_cdr3_aa", 'secondary_TRB_cdr3_aa', 'secondary_TRA_cdr3_aa')) |> 
    group_by(clonotype_id, 
             TRA_cdr3_aa, TRB_cdr3_aa, 
             secondary_TRB_cdr3_aa, secondary_TRA_cdr3_aa,
             clonotype_count,
             TRA_V, TRA_D, TRA_J, TRB_V, TRB_D, TRB_J) |>  # no c genes 
    summarize(cells = paste0(Barcode, collapse=',')) |> 
    arrange(desc(clonotype_count)) |>
    ungroup() |>
     mutate(across(
    c(TRA_V, TRA_D, TRA_J, TRB_V, TRB_D, TRB_J),
    ~ ifelse(. %in% c("nan", "NaN") | is.nan(.), NA, .)
  )) |> mutate(
    chain = case_when(
      !is.na(TRB_cdr3_aa) & !is.na(TRA_cdr3_aa) & is.na(secondary_TRB_cdr3_aa) & is.na(secondary_TRA_cdr3_aa) ~ 'TRA;TRB',
      is.na(TRB_cdr3_aa) & !is.na(TRA_cdr3_aa) & is.na(secondary_TRB_cdr3_aa) & is.na(secondary_TRA_cdr3_aa) ~ 'TRA',
      !is.na(TRB_cdr3_aa) & is.na(TRA_cdr3_aa) & is.na(secondary_TRB_cdr3_aa) & is.na(secondary_TRA_cdr3_aa) ~ 'TRB',
      is.na(TRB_cdr3_aa) & !is.na(TRA_cdr3_aa) & is.na(secondary_TRB_cdr3_aa) & !is.na(secondary_TRA_cdr3_aa) ~ 'TRA;TRA',
      !is.na(TRB_cdr3_aa) & is.na(TRA_cdr3_aa) & !is.na(secondary_TRB_cdr3_aa) & is.na(secondary_TRA_cdr3_aa) ~ 'TRB;TRB',
      !is.na(TRB_cdr3_aa) & !is.na(TRA_cdr3_aa) & !is.na(secondary_TRB_cdr3_aa) & is.na(secondary_TRA_cdr3_aa) ~ 'TRA;TRB;TRB',
      !is.na(TRB_cdr3_aa) & !is.na(TRA_cdr3_aa) & is.na(secondary_TRB_cdr3_aa) & !is.na(secondary_TRA_cdr3_aa) ~ 'TRA;TRA;TRB',
      !is.na(TRB_cdr3_aa) & !is.na(TRA_cdr3_aa) & !is.na(secondary_TRB_cdr3_aa) & !is.na(secondary_TRA_cdr3_aa) ~ 'TRA;TRA;TRB;TRB',
      .default = 'error'
  )) |>
    mutate(
      CDR3.aa=paste0(TRA_cdr3_aa, ';', TRB_cdr3_aa),
      V.name=paste0(TRA_V, ';', TRB_V),
           D.name=paste0(TRA_D, ';', TRB_D),
           J.name=paste0(TRA_J, ';', TRB_J),
      .keep='unused') |>
    rename('Clones' = clonotype_count) |> 
    mutate(
      Proportion = Clones / sum(Clones),
      CDR3.nt = NA,
      V.end = NA,
      D.start = NA,
      D.end = NA,
      J.start = NA,
      VJ.ins = NA,
      VD.ins = NA,
      DJ.ins = NA,
      Sequence = NA
    ) |>
    arrange(desc(Clones)) |>
    select(Clones, Proportion, CDR3.nt, CDR3.aa, V.name, D.name, J.name, V.end, D.start, D.end, J.start, VJ.ins, VD.ins, DJ.ins, Sequence, everything())
  barcode_report
}
```


```{r}
kit <- 'parse_v2'
for (i in 1:nrow(samplesheets[[kit]])){
  sample <- samplesheets[[kit]][i,'Sample']
  file <- samplesheets[[kit]][i,'File']
  
  # vdj_data <- file.path(config$base_dir, config$data_dir,  data_dirs[[kit]],'TCR/COMBINED/', file, 'TCR_filtered/tcr_annotation_airr.tsv')
  # filtered_counts <- read.table(vdj_data, sep='\t', header = TRUE)
  vdj_data <- file.path(config$base_dir, config$data_dir,  data_dirs[[kit]],'TCR/COMBINED/', file, 'TCR_filtered/barcode_report.tsv')
  vdj_data <- repload_parse(vdj_data)
  objs[[sample]] <- list(data=vdj_data, metadata=tibble())
}
```

# Read metric summaries

```{r}
metric_summaries <- list()
```

## gemx_5p

```{r}
kit <- 'gemx_5p'
for (i in 1:nrow(samplesheets[[kit]])){
  sample <- samplesheets[[kit]][i,'Sample']
  file <- samplesheets[[kit]][i,'File']
  
  vdj_data <- file.path(config$base_dir, config$data_dir, data_dirs[[kit]], file,
                               'outs', 'per_sample_outs', file, 'metrics_summary.csv')
  vdj_data <- read.csv(vdj_data)
  metric_summaries[[sample]] <- vdj_data
}
```

## nextgem_5p

```{r}
kit <- 'nextgem_5p'
for (i in 1:nrow(samplesheets[[kit]])){
  sample <- samplesheets[[kit]][i,'Sample']
  file <- samplesheets[[kit]][i,'File']
  vdj_data <- file.path(config$base_dir, config$data_dir, data_dirs[[kit]], file,
                               'outs', 'per_sample_outs', file, 'metrics_summary.csv')
  vdj_data <- read.csv(vdj_data)
  metric_summaries[[sample]] <- vdj_data
}
metric_summaries$NextGEM5P_F1 |> View()
```

## parse_v2

```{r}
kit <- 'parse_v2'
for (i in 1:nrow(samplesheets[[kit]])){
  sample <- samplesheets[[kit]][i,'Sample']
  file <- samplesheets[[kit]][i,'File']
  
  vdj_data <- file.path(config$base_dir, config$data_dir,  data_dirs[[kit]],'TCR/COMBINED/', file, 'report/sample_all_stats.csv')
  vdj_data <- read.csv(vdj_data)
  metric_summaries[[sample]] <- vdj_data |> select(statistic, combined)
}
```

## Trimming

```{r}
trimmed_metric_summaries_parse <- lapply(metric_summaries[metadata$Sample[metadata$Kit=='Parse_v2']], function(x) {
  x |> filter(statistic %in% c(
    'tcr_number_of_cells', 
    'tcr_tcells_with_productive_TRA',
    'tcr_tcells_with_productive_TRB',
    'tcr_tcells_with_productive_pair'
  )) |>
    mutate(pct = 100 * combined / x$combined[x$statistic == 'tcr_number_of_cells']) |>
    rename('Metric.Name' = statistic, 
           'Metric.Value' = combined) |>
    mutate(Metric.Name = case_when(
      Metric.Name == 'tcr_number_of_cells' ~ 'Total cells',
      Metric.Name == 'tcr_tcells_with_productive_TRA' ~ 'TRA', 
      Metric.Name == 'tcr_tcells_with_productive_TRB' ~ 'TRB',
      Metric.Name == 'tcr_tcells_with_productive_pair' ~ 'TRA & TRB'
    ))
}) |> rbindlist(idcol = 'Sample')
trimmed_metric_summaries_10x <- lapply(metric_summaries[metadata$Sample[metadata$Kit!='Parse_v2']], function(x) {
  x |> 
    filter(Metric.Name %in% c(
    'Estimated number of cells',
    'Cells with productive TRA contig', 
    'Cells with productive TRB contig',
    'Cells with productive V-J spanning (TRA, TRB) pair'
  ) & Category == 'Cells') |>
    mutate(Metric.Value = readr::parse_number(Metric.Value)) %>%
    mutate(value = ifelse(Metric.Name != 'Estimated number of cells', 
                      round(Metric.Value / 100 * .$Metric.Value[.$Metric.Name == 'Estimated number of cells']),
                      Metric.Value)) |>
    rename(pct = Metric.Value, Metric.Value = value) |>
    mutate(pct = ifelse(Metric.Name == 'Estimated number of cells',100, pct)) |>
    mutate(Metric.Name = case_when(
      Metric.Name == 'Estimated number of cells' ~ 'Total cells',
      Metric.Name == 'Cells with productive TRA contig' ~ 'TRA', 
      Metric.Name == 'Cells with productive TRB contig' ~ 'TRB',
      Metric.Name == 'Cells with productive V-J spanning (TRA, TRB) pair' ~ 'TRA & TRB'
    )) |>
    select(Metric.Name, Metric.Value, pct)
}) |> rbindlist(idcol='Sample')

trimmed_metric_summaries <- rbind(trimmed_metric_summaries_10x, trimmed_metric_summaries_parse)
```

# Cell recovery



# clone recovery

## Reported

```{r}
plotdata <- merge(trimmed_metric_summaries, metadata, by='Sample')
ggplot(filter(plotdata, Metric.Name != 'Total cells'), aes(x=Metric.Name, y=pct)) +
  geom_boxplot() +
  geom_beeswarm(aes(shape=Individual)) +
  facet_wrap(~ Kit) +
  labs(x='Chain(s)', y='Recovery (% of T cells)') ->
figures[['reported chain recovery']]
figures[['reported chain recovery']]
```

## counts

```{r}
plotdata <- data.table::rbindlist(lapply(objs, function(x) {
  x$data |>
    group_by(chain) |>
    summarize(n=n())
}), idcol = 'Sample') |>
  merge(metadata, by='Sample') |>
  mutate(chain = factor(chain, levels = c(
    'TRA;TRB',
    'TRA',
    'TRB',
    'TRA;TRA;TRB',
    'TRA;TRB;TRB',
    'TRA;TRA',
    'TRB;TRB',
    'TRA;TRA;TRB;TRB'
  )))
ggplot(plotdata, aes(x=chain, y=n)) +
  geom_boxplot() +
  geom_point(aes(shape = Individual)) +
  facet_wrap(~ Kit, scales='free_x') +
  theme(axis.text.x = element_text(angle=45, hjust=1, vjust=1)) +
  labs(x='Chain(s)', y='Cell count') ->
  figures[['chain recovery count']]
figures[['chain recovery count']]
```

## proportions

### All cells

```{r}
return_total_cells <- function(sample){
  trimmed_metric_summaries$Metric.Value[
    trimmed_metric_summaries$Sample == sample &
    trimmed_metric_summaries$Metric.Name == 'Total cells'
  ] 
}

plotdata <- data.table::rbindlist(lapply(objs, function(x) {
  x$data |>
    group_by(chain) |>
    summarize(n=n())
}), idcol = 'Sample') |>
  merge(metadata, by='Sample') |>
  mutate(chain = factor(chain, levels = c(
    'TRA;TRB',
    'TRA',
    'TRB',
    'TRA;TRA;TRB',
    'TRA;TRB;TRB',
    'TRA;TRA',
    'TRB;TRB',
    'TRA;TRA;TRB;TRB'
  ))) |>
  group_by(Sample)
plotdata$prop <- plotdata$n / unlist(lapply(plotdata$Sample, return_total_cells))
ggplot(plotdata, aes(x=chain, y=prop)) +
  geom_boxplot() +
  geom_point(aes(shape = Individual)) +
  scale_y_continuous(labels=scales::percent) +
  facet_wrap(~ Kit, scales='free_x') +
  theme(axis.text.x = element_text(angle=45, hjust=1, vjust=1)) +
  labs(x='Chain(s)', y='% of cells', caption='% of all detected T cells regardless of chain recovery') ->
  figures[['chain recovery % all T']]
figures[['chain recovery % all T']]
```

### Cells with productive chains

```{r}
plotdata <- data.table::rbindlist(lapply(objs, function(x) {
  x$data |>
    group_by(chain) |>
    summarize(n=n())
}), idcol = 'Sample') |>
  merge(metadata, by='Sample') |>
  mutate(chain = factor(chain, levels = c(
    'TRA;TRB',
    'TRA',
    'TRB',
    'TRA;TRA;TRB',
    'TRA;TRB;TRB',
    'TRA;TRA',
    'TRB;TRB',
    'TRA;TRA;TRB;TRB'
  ))) |>
  group_by(Sample) |>
  mutate(prop = n / sum(n))
ggplot(plotdata, aes(x=chain, y=prop)) +
  geom_boxplot() +
  geom_point(aes(shape = Individual)) +
  scale_y_continuous(labels=scales::percent) +
  facet_wrap(~ Kit, scales='free_x') +
  theme(axis.text.x = element_text(angle=45, hjust=1, vjust=1)) +
  labs(x='Chain(s)', y='% of cells', caption='Only considering cells with recovered chains') ->
  figures[['chain recovery % recovered']]
figures[['chain recovery % recovered']]
```

# Richness

```{r, eval=FALSE}
plotdata <- lapply(objs, function(x){
  nrow(x$data)
}) |>
  as.data.table() |>
  melt() |>
  merge(metadata, by.x='variable', by.y='Sample') 

plotdata$total_cells <- unlist(lapply(plotdata$variable, return_total_cells))
plotdata$ratio <- plotdata$value / plotdata$total_cells

ggplot(plotdata, aes(x=Individual)) +
  geom_col(aes(y=value)) + 
  geom_point(aes(y=total_cells), shape=95, size=20, color = 'darkblue') +
  facet_wrap(~ Kit) + 
  labs(x= 'Sample', y='Unique clonotypes', caption='Blue line shows total T cells recovered (with or without productive chains') ->
  figures[['unique clone recovery count']]
figures[['unique clone recovery count']]
```


```{r, eval = FALSE}
plotdata <- lapply(objs, function(x){
  nrow(x$data)
}) |>
  as.data.table() |>
  melt() |>
  merge(metadata, by.x='variable', by.y='Sample') 

plotdata$total_cells <- unlist(lapply(plotdata$variable, return_total_cells))
plotdata$ratio <- plotdata$value / plotdata$total_cells

ggplot(plotdata, aes(x=Individual)) +
  geom_col(aes(y=ratio)) + 
  # geom_point(aes(y=total_cells), shape=95, size=20, color = 'darkblue') +
  facet_wrap(~ Kit) + 
  labs(x= 'Sample', y='Unique clonotypes ratio', caption = 'Unique clonotypes / total T cells') ->
  figures[['unique clone recovery ratio']]
figures[['unique clone recovery ratio']]
```


# Diversity 

```{r}
plotdata <- lapply(objs, function(x) repDiversity(x$data, 'inv.simp')) |>
  as.data.table() |>
  melt() |>
  merge(metadata, by.x='variable', by.y='Sample') 
ggplot(plotdata, aes(x=Individual, y=value)) +
  geom_col() +
  facet_wrap(~ Kit) +
  labs(x='Individual', y='Inverse Simpson index') ->
  figures[['simpson index']]
figures[['simpson index']]
```


# Render report

```{r, eval=TRUE}
## This only works if all the variables called in the format file 
## are in the current environment. Check the format file to tweak
## aesthetics 
rmarkdown::render(here('processing_scripts/5p/wt/01-tcr_analysis.format.Rmd'),
                  output_file = '01-clone_qc.html',
                  output_dir = here('reports/5p/wt/'))
```